#ifndef EEPROM_MEM_LOCATION_H
#define EEPROM_MEM_LOCATION_H

#define E_MEM_RED 0
#define E_MEM_GREEN 1
#define E_MEM_BLUE 2
#define E_MEM_WHITE 3

#define E_MEM_MRED 4
#define E_MEM_MGREEN 5
#define E_MEM_MBLUE 6
#define E_MEM_MWHITE 7

#define E_MEM_SPARE_MIN_EN 8
#define E_MEM_TEMPERATURE_DIS_EN 9
#define E_MEM_AUTO_BRIGHTNESS 10

#endif //EEPROM_MEM_LOCATION_H